version: '3.9'

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: ./requirements/mariadb/data
            type: none
            o: bind
    nginx:
        name: nginx
        driver: local
        driver_opts:
            device: ./requirements/nginx/logs
            type: none
            o: bind
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: ./requirements/wordpress/html
            type: none
            o: bind

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
        restart: always
        tty: true
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - nginx:/var/log/nginx
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart: always
        tty: true
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart: always
        tty: true

networks:
    inception:
        name: inception